[build-system]
requires = ["setuptools"]

[project]
dependencies = [
    "projectcard",
    "pyyaml",
]

[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"