minimum_allowable_node_id: 1
maximum_allowable_node_id: 400000
minimum_allowable_link_id: 1
maximum_allowable_link_id: 1500000
nodes_used_by_geography:
  - geography_name: All
    start: 0
    end: 354385
links_used_by_geography:
  - geography_name: All
    start: 0
    end: 1189304
