minimum_allowable_node_id: 1
maximum_allowable_node_id: 1000000
minimum_allowable_link_id: 1
maximum_allowable_link_id: 2000000
nodes_used_by_geography:
  - geography_name: All
    start: 0
    end: 672000
links_used_by_geography:
  - geography_name: All
    start: 0
    end: 1422000
